# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-31 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tommymovies', '0005_auto_20170126_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='douban_url',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_url',
            field=models.CharField(default='url', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='rt_url',
            field=models.CharField(default='ur;', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='movie_categories', to='tommymovies.Category'),
        ),
    ]
