# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-03 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tommymovies', '0006_auto_20170131_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='p_rating',
            field=models.IntegerField(blank=True),
        ),
    ]
