# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-03 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tommymovies', '0007_auto_20170202_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='douban_url',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_url',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='movie',
            name='p_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rt_rating',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rt_url',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
