# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tommymovies', '0010_movie_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='comment',
        ),
    ]
