# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tommymovies', '0012_movie_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='watch_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
