# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tommymovies', '0017_auto_20170207_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='movie_categories', to='tommymovies.Category'),
        ),
    ]
