# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-08 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tommymovies', '0018_auto_20170207_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_img',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
