# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-20 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('watched', models.BooleanField()),
                ('watch_date', models.DateTimeField(verbose_name='Date Watched')),
                ('p_rating', models.IntegerField()),
                ('imdb_rating', models.FloatField()),
                ('rt_rating', models.FloatField()),
            ],
        ),
    ]
